Making changes in an attempt to improve CI pipeline.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -6,31 +6,34 @@ deploy:
   image: $GIT_IMAGE
   before_script:
     # Install git
-    - apk update && apk add git
+    - apk update && apk add --no-cache git
 
-    # Configure required variables and settings
+    # Configure required Git identity
     - git config --global user.name "${FULL_NAME}"
     - git config --global user.email "${EMAIL}"
-    - |
-      if ! git symbolic-ref -q HEAD; then
-        echo "Detached HEAD detected. Attempting to fix..."
-        git checkout -B $CI_COMMIT_BRANCH
-      fi
-    - git branch --set-upstream-to=origin/$CI_COMMIT_BRANCH
 
   script:
-    # Push to GitHub
-    - git remote set-url github https://${GITHUB_TOKEN}@github.com/${GIT_USER}/${CI_PROJECT_NAME}.git 2>/dev/null ||
-      git remote add github https://${GITHUB_TOKEN}@github.com/${GIT_USER}/${CI_PROJECT_NAME}.git
-    - git push github
+    # GitHub remote
 
-    # Push to GitLab
-    - git remote set-url gitlab https://gitlab-ci-token:${GITLAB_TOKEN}@gitlab.com/${GIT_USER}/${CI_PROJECT_NAME}.git 2>/dev/null ||
-      git remote add gitlab https://gitlab-ci-token:${GITLAB_TOKEN}@gitlab.com/${GIT_USER}/${CI_PROJECT_NAME}.git
-    - git push gitlab
+    - |
+      if git remote | grep -q github; then
+        git remote set-url github https://${GITHUB_TOKEN}@github.com/${GIT_USER}/${CI_PROJECT_NAME}.git
+      else
+        git remote add github https://${GITHUB_TOKEN}@github.com/${GIT_USER}/${CI_PROJECT_NAME}.git
+      fi
+    - git push -u github $CI_COMMIT_BRANCH
 
-    # Remove remotes to avoid caching issues
-    - echo "Starting cleanup..."
-    - git remote remove github
-    - git remote remove gitlab
-    - echo "Cleanup completed."
+    # GitLab remote
+
+    - |
+      if git remote | grep -q gitlab; then
+        git remote set-url gitlab https://gitlab-ci-token:${GITLAB_TOKEN}@gitlab.com/${GIT_USER}/${CI_PROJECT_NAME}.git
+      else
+        git remote add gitlab https://gitlab-ci-token:${GITLAB_TOKEN}@gitlab.com/${GIT_USER}/${CI_PROJECT_NAME}.git
+      fi
+    - git push -u gitlab $CI_COMMIT_BRANCH
+
+    # Cleanup remotes to avoid caching issues
+    - git remote remove github || true
+    - git remote remove gitlab || true
+
